#!/bin/bash -e

SRCDIR=$(cd "$(dirname $0)/."  && pwd)
TGTDIR=$(cd "$(dirname $0)/." && pwd)
NAME=$(basename "$SRCDIR" | sed s/-/_/g)
ZIPFILE="$TGTDIR/$NAME.zip"

cf delete-buildpack -f "$NAME"
cf create-buildpack "$NAME" "$ZIPFILE" 99 --enable